### ISSUE TITLE
Each only returns one record

### ISSUE THREAD

**Issue by drluckyspin** [chjj/tiny#2] opened 2012-02-14 07:08 UTC
I am trying to use the each method to iterate on all of the records, but it only appears to be getting called once. This is what I'm using:

tinyDB.each(function(record) {
    var currentRecord = [record.timestamp, record._key, record.value];
    console.log("Current record = " + currentRecord);

  }, function() {
    console.log('done with loading objects');
  }, true
);

Am I missing something?

Thanks

**Comment by chjj** [comment] 2012-02-15 03:14
Not sure, I can't reproduce this. What do you see when you put a `console.log(tinyDB._cache)` in your code?

**Comment by chjj** [comment] 2012-06-10 18:29
Closing for now.

**Closed as completed by chjj** 2012-06-10 18:29 UTC
